<?php
namespace Tests\Browser;

use App\Models\User;
use App\Models\Event;
use App\Models\Ticket;
use Laravel\Dusk\Browser;
use Tests\DuskTestCase;

class TicketManagementTest extends DuskTestCase
{
    public function test_event_ticket_generation_on_creation()
    {
        $response = $this->post(route('manage-events.store'), [
            'name' => 'Test Event with Tickets',
            'startDateTime' => now(),
            'endDateTime' => now()->addHours(1),
            'policyIds' => ['policy_id_1'],
            'nonceValidForMinutes' => 10,
            'hodlAsset' => true,  // Ensure ticket generation
        ]);

        $event = Event::where('name', 'Test Event with Tickets')->first();
        $this->assertNotNull($event);
        $this->assertEquals(5, $event->tickets()->count());  // Assuming 5 tickets are generated by default
    }


    public function test_ticket_status_updates_reflected_in_ui()
    {
        $this->browse(function (Browser $browser) {
            $user = User::factory()->create();
            $event = Event::factory()->create();
            $ticket = Ticket::factory()->create(['event_id' => $event->id]);

            $browser->actingAs($user)
                ->visit("/staff/scan-tickets/{$event->uuid}")
                ->press('Register Ticket')
                ->waitForText('Ticket successfully registered')
                ->assertTrue($ticket->fresh()->isCheckedIn)
                ->assertSee('Checked In'); // Added check to see the status update in UI
        });
    }
}
